# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-05 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilityoccurrence',
            name='end',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='availabilityoccurrence',
            name='start',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='busy',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start',
            field=models.DateTimeField(db_index=True),
        ),
    ]
