# Generated by Django 2.1.7 on 2019-03-22 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_agenda', '0003_padding'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='availabilityoccurrence',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'managed': False},
        ),
    ]
